### ISSUE TITLE
importError: No module named sox

### ISSUE THREAD

**Issue by vinodkkurmi** [marl/audiosetdl#25]
I am getting the error importError: No module named sox
after installing sox package form the 

conda install -c conda-forge -y sox

Can someone help ...
thanks

**Comment by justinsalamon** [comment]
`conda install -c conda-forge -y sox` will install the command-line sox tool (which you need), but you also need the python module: `pip install pysox`. Let us know if this solves your problem, cheers.

**Comment by justinsalamon** [comment]
@vinodkkurmi we've pushed an update that should fix this, can you try again (with the latest source) and confirm?

**Comment by eldrin** [comment]
Hi, in my case (ubuntu18.04 / python3.6) the `pip` couldn't find the `pysox`. I succeed to install the environment with manually running `pip install sox==1.3.3`.

**Comment by justinsalamon** [comment]
Thanks @eldrin for spotting this, indeed the module is registered on pypi as `sox`, not `pysox`. I'll push a fix shortly.

**Comment by justinsalamon** [comment]
@eldrin just pushed the fix - could you please try installing again from scratch to confirm the issue doesn't happen any more? thanks

**Comment by eldrin** [comment]
@justinsalamon Now the installation is working smoothly! I have not used the actual downloader yet but will do soon as well. Thanks for the timely response as well :)

**Comment by justinsalamon** [comment]
Thanks @eldrin for confirming, closing this out. If you have any issues when using the downloader please post a new issue. Thanks.
