### ISSUE TITLE
Skeleton notebook to visualize audio and video frames

### ISSUE THREAD

**Issue by hohsiangwu** [marl/audiosetdl#3]
Per our discussion yesterday, I have pushed a notebook with two sample video and audio files in the `notebooks` folder with basic functions you can find here in [rendered](https://github.com/marl/audiosetdl/blob/master/notebooks/download.ipynb).

Couple notes:
- `pafy` recommend that we use `youtube_dl` backend since `youtube_dl` updates more often.
- Mainly I am using `pafy` to get the urls, `opencv-python` to input video and `SoundFile ` to input audio. Dependencies are all in the `requirements.txt`.

/cc @jtcramer Let me know if this makes sense for you to plug in the FFmpeg call out.
/cc @justinsalamon FYI

**Comment by jtcramer** [comment]
I wasn't able to get OpenCV working properly on my machine, but I was able to get `scikit-video` to work. With all of that, all of the features should be there to exemplify downloading and loading the data.
