### ISSUE TITLE
encoder 'aac' is experimental

### ISSUE THREAD

**Issue by satyamr1** [marl/audiosetdl#33]
I am stuck at the following error: 

ERROR - Got non-zero exit code (1) from command "/usr/bin/ffmpeg": [aac @ 0x24a7820] The encoder 'aac' is experimental but experimental codecs are not enabled, add '-strict -2' if you want to use it.
. Retrying...

can anyone please help with the error!

**Comment by Cocoxili** [comment]
@satyamr1 You can upgrade your ffmpeg. If you're seeing the "experimental" message then your ffmpeg is old.
