### ISSUE TITLE
Verify audio/video file to make sure it's correct length, and other sanity checks

### ISSUE THREAD

**Issue by jtcramer** [marl/audiosetdl#9]

**Comment by jtcramer** [comment]
Look into md5?

**Comment by hohsiangwu** [comment]
I have added an example to sanity check at least bitrate, channels, fs, format, and duration with `sox` in the [notebook](https://github.com/marl/audiosetdl/commit/9727b55a2c172995ccaed694e09b8889f9f74aee).

Already checked that sox is installed on prince, therefore if we are going this route, we can just add pysox into the requirements.txt

**Comment by jtcramer** [comment]
ffmpeg comes with ffprobe, which we could use that as well. Though if sox is already installed, we have the benefit of using pysox rather than parsing ffprobe's output.

**Comment by jtcramer** [comment]
Checks have been added
